/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * used to send text to a text-only or text mode graphics display. POSTing a string of text to the text resource causes it to be displayed at the selected X and Y locations on the display. If X or Y are set to a value greater than the size of the display, the position “wraps around” to the modulus of the setting and the display size. Likewise, if the text string overflows the display size, the text “wraps around” and displays on the next line down or, if the last line has been written, wraps around to the top of the display. Brightness and Contrast controls are provided to allow control of various display types including STN and DSTN type LCD character displays. POSTing an empty payload to the Clear Display resource causes the display to be erased.
 */
export interface AddressableTextDisplay {
  /**
   * A string of text.
   */
  "5527"?: string;
  /**
   * X Coordinate.
   */
  "5528"?: number;
  /**
   * Y Coordinate.
   */
  "5529"?: number;
  /**
   * Command to clear the display.
   */
  "5530"?: string;
  /**
   * Proportional control, integer value between 0 and 100 as a percentage.
   */
  "5531"?: number;
  /**
   * The highest X coordinate the display supports before wrapping to the next line.
   */
  "5545"?: number;
  /**
   * The highest Y coordinate the display supports before wrapping to the next line.
   */
  "5546"?: number;
  /**
   * Input/output level control, float value between 0 and 100 as a percentage.
   */
  "5548"?: number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
  /**
   * This resource represents a power source, which can be controlled, the setting of which is a Boolean value (1,0) where 1 is on and 0 is off
   */
  "5850"?: boolean;
}
