/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Generic analog input for non-specific sensors
 */
export interface AnalogInput {
  /**
   * The current value of the analog input.
   */
  "5600"?: number;
  /**
   * The minimum value that can be measured by the sensor
   */
  "5601"?: number;
  /**
   * The maximum value that can be measured by the sensor.
   */
  "5602"?: number;
  /**
   * The minimum value that can be measured by the sensor.
   */
  "5603"?: number;
  /**
   * The maximum value that can be measured by the sensor.
   */
  "5604"?: number;
  /**
   * Reset the Min and Max Measured Values to Current Value.
   */
  "5605"?: string;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
  /**
   * The type of the sensor (for instance PIR type).
   */
  "5751"?: string;
}
