/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * used for a speaker that plays a pre-recorded audio clip or an audio output that is sent elsewhere. For example, an elevator which announces the floor of the building. A resource is provided to store the clip, a dimmer resource controls the relative sound level of the playback, and a duration resource limits the maximum playback time. After the duration time is reached, any remaining samples in the clip are ignored, and the clip player will be ready to play another clip.
 */
export interface AudioClip {
  /**
   * Audio Clip that is playable (i.e. short audio recording indicating the floor in an elevator).
   */
  "5522"?: {
    [k: string]: any;
  };
  /**
   * Trigger initiating actuation.
   */
  "5523"?: string;
  /**
   * The duration of the sound once trigger.
   */
  "5524"?: number;
  /**
   * Input/output level control, float value between 0 and 100 as a percentage.
   */
  "5548"?: number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
}
