/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cell blacklist information
 */
export interface CellBlacklistEvent {
  /**
   * EARFCN - frequency
   */
  "6032"?: number;
  /**
   * Cell Identity
   */
  "6033"?: number;
}
