/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * cell reselection event information
 */
export interface CellReselectionEvent {
  /**
   * IMEI of device
   */
  "2"?: string;
  /**
   * IMSI of device
   */
  "3"?: string;
  /**
   * EARFCN - frequency
   */
  "6032"?: number;
  /**
   * Cell Identity
   */
  "6033"?: number;
}
