/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Generic digital output for non-specific actuators
 */
export interface DigitalOutput {
  /**
   * The current state of a digital output,  0=OFF, 1=ON..
   */
  "5550": boolean;
  /**
   * The polarity of a digital ouput as a Boolean (0 = Normal, 1= Reversed).
   */
  "5551": boolean;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750": string;
}
