/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * report the current reading of a gyrometer sensor in 3 axes. It provides tracking of the minimum and maximum angular rate in all 3 axes. An example unit of measure is radians per second (ucum:rad/s)
 */
export interface Gyrometer {
  /**
   * The minimum measured value along the X axis.
   */
  "5508"?: number;
  /**
   * The maximum measured value along the X axis.
   */
  "5509"?: number;
  /**
   * The minimum measured value along the Y axis.
   */
  "5510"?: number;
  /**
   * The maximum measured value along the Y axis.
   */
  "5511"?: number;
  /**
   * The minimum measured value along the Z axis.
   */
  "5512"?: number;
  /**
   * The maximum measured value along the Z axis.
   */
  "5513"?: number;
  /**
   * The minimum value that can be measured by the sensor.
   */
  "5603"?: number;
  /**
   * The maximum value that can be measured by the sensor.
   */
  "5604"?: number;
  /**
   * Reset the Min and Max Measured Values to Current Value.
   */
  "5605"?: string;
  /**
   * If present, the type of sensor defined as the UCUM Unit Definition e.g. “Cel” for Temperature in Celcius.
   */
  "5701"?: string;
  /**
   * The measured value along the X axis.
   */
  "5702"?: number;
  /**
   * The measured value along the Y axis.
   */
  "5703"?: number;
  /**
   * The measured value along the Z axis.
   */
  "5704"?: number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
}
