/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * handover event information
 */
export interface HandoverEvent {
  /**
   * IMSI of device
   */
  "3"?: string;
  /**
   * MSISDN of device
   */
  "4"?: string;
  /**
   * EARFCN - frequency
   */
  "6032"?: number;
  /**
   * Cell Identity
   */
  "6033"?: number;
}
