/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * report the position of a shuttle or joystick control. A digital input is provided to report the state of an associated push button.
 */
export interface MultipleAxisJoystick {
  /**
   * The current state of a digital input.
   */
  "5500": boolean;
  /**
   * The cumulative value of active state detected.
   */
  "5501": number;
  /**
   * The measured value along the X axis.
   */
  "5702": number;
  /**
   * The measured value along the Y axis.
   */
  "5703": number;
  /**
   * The measured value along the Z axis.
   */
  "5704": number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750": string;
}
