/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * represent the state of a Multi-state selector switch with a number of fixed positions.
 */
export interface MultistateSelector {
  /**
   * The current state of a Multi-state input or selector.
   */
  "5547"?: number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
}
