/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * OMA resources schema
 */
export interface OMAResources {
  /**
   * The tool version that the device supports - used to determine the logging object/resource version to be used for parsing
   */
  "1"?: string;
  /**
   * IMEI of device
   */
  "2"?: string;
  /**
   * IMSI of device
   */
  "3"?: string;
  /**
   * MSISDN of device
   */
  "4"?: string;
  /**
   * Human-readable name of the device
   */
  "10"?: string;
  /**
   * The current state of a digital input.
   */
  "5500"?: boolean;
  /**
   * The cumulative value of active state detected.
   */
  "5501"?: number;
  /**
   * The polarity of the digital input as a Boolean (0 = Normal, 1= Reversed).
   */
  "5502"?: boolean;
  /**
   * The debounce period in ms.
   */
  "5503"?: number;
  /**
   * The edge selection as an integer (1 = Falling edge, 2 = Rising edge, 3 = Both Rising and Falling edge).
   */
  "5504"?: number;
  /**
   * Reset the Counter value.
   */
  "5505"?: string;
  /**
   * Unix Time. A signed integer representing the number of seconds since Jan 1st, 1970 in the UTC time zone.
   */
  "5506"?: string;
  /**
   * For shorter times of a fraction of a second (i.e. 0.23).
   */
  "5507"?: number;
  /**
   * The minimum measured value along the X axis.
   */
  "5508"?: number;
  /**
   * The maximum measured value along the X axis.
   */
  "5509"?: number;
  /**
   * The minimum measured value along the Y axis.
   */
  "5510"?: number;
  /**
   * The maximum measured value along the Y axis.
   */
  "5511"?: number;
  /**
   * The minimum measured value along the Z axis.
   */
  "5512"?: number;
  /**
   * The maximum measured value along the Z axis.
   */
  "5513"?: number;
  /**
   * The decimal notation of latitude, e.g. -43.5723 (World Geodetic System 1984).
   */
  "5514"?: string;
  /**
   * The decimal notation of longitude, e.g. 153.21760 (World Geodetic System 1984).
   */
  "5515"?: string;
  /**
   * The accuracy of the position in meters.
   */
  "5516"?: string;
  /**
   * The velocity of the device as defined in 3GPP 23.032 GAD specification. This set of values may not be available if the device is static.
   */
  "5517"?: {
    [k: string]: any;
  };
  /**
   * The timestamp of when the location measurement was performed.
   */
  "5518"?: string;
  /**
   * The minimum value that can be measured by the sensor.
   */
  "5519"?: number;
  /**
   * The maximum value that can be measured by the sensor.
   */
  "5520"?: number;
  /**
   * The duration of the time delay.
   */
  "5521"?: number;
  /**
   * Audio Clip that is playable (i.e. short audio recording indicating the floor in an elevator).
   */
  "5522"?: {
    [k: string]: any;
  };
  /**
   * Trigger initiating actuation.
   */
  "5523"?: string;
  /**
   * The duration of the sound once trigger.
   */
  "5524"?: number;
  /**
   * The off time when On/Off control remains on.
   */
  "5525"?: number;
  /**
   * type of timer pattern used by the patterns.
   */
  "5526"?: number;
  /**
   * A string of text.
   */
  "5527"?: string;
  /**
   * X Coordinate.
   */
  "5528"?: number;
  /**
   * Y Coordinate.
   */
  "5529"?: number;
  /**
   * Command to clear the display.
   */
  "5530"?: string;
  /**
   * Proportional control, integer value between 0 and 100 as a percentage.
   */
  "5531"?: number;
  /**
   * Indicates an increase control action.
   */
  "5532"?: boolean;
  /**
   * Indicates an decrease control action.
   */
  "5533"?: boolean;
  /**
   * Counts the number of times the timer output transitions from 0 to 1.
   */
  "5534"?: number;
  /**
   * Current position or desired position of a positioner actuator.
   */
  "5536"?: number;
  /**
   * The time expected to move the actuator to the new position.
   */
  "5537"?: number;
  /**
   * The time remaining in an operation.
   */
  "5538"?: number;
  /**
   * Counts the number of times the increase control has been operated. Writing a 0 resets the counter.
   */
  "5541"?: number;
  /**
   * Counts the times the decrease control has been operated. Writing a 0 resets the counter
   */
  "5542"?: number;
  /**
   * The current state of the timer output.
   */
  "5543"?: boolean;
  /**
   * The total time in seconds that the timer input is true. Writing a 0 resets the time.
   */
  "5544"?: number;
  /**
   * The highest X coordinate the display supports before wrapping to the next line.
   */
  "5545"?: number;
  /**
   * The highest Y coordinate the display supports before wrapping to the next line.
   */
  "5546"?: number;
  /**
   * The current state of a Multi-state input or selector.
   */
  "5547"?: number;
  /**
   * Input/output level control, float value between 0 and 100 as a percentage.
   */
  "5548"?: number;
  /**
   * The current state of a digital output,  0=OFF, 1=ON..
   */
  "5550"?: boolean;
  /**
   * The polarity of a digital ouput as a Boolean (0 = Normal, 1= Reversed).
   */
  "5551"?: boolean;
  /**
   * The current value of the analog input.
   */
  "5600"?: number;
  /**
   * The minimum value that can be measured by the sensor
   */
  "5601"?: number;
  /**
   * The maximum value that can be measured by the sensor.
   */
  "5602"?: number;
  /**
   * The minimum value that can be measured by the sensor.
   */
  "5603"?: number;
  /**
   * The maximum value that can be measured by the sensor.
   */
  "5604"?: number;
  /**
   * Reset the Min and Max Measured Values to Current Value.
   */
  "5605"?: string;
  /**
   * The current state of the analogue output.
   */
  "5650"?: number;
  /**
   * Last or Current Measured Value from the Sensor.
   */
  "5700"?: number;
  /**
   * If present, the type of sensor defined as the UCUM Unit Definition e.g. “Cel” for Temperature in Celcius.
   */
  "5701"?: string;
  /**
   * The measured value along the X axis.
   */
  "5702"?: number;
  /**
   * The measured value along the Y axis.
   */
  "5703"?: number;
  /**
   * The measured value along the Z axis.
   */
  "5704"?: number;
  /**
   * The compass direction.
   */
  "5705"?: number;
  /**
   * A string representing a value in some color space
   */
  "5706"?: string;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
  /**
   * The type of the sensor (for instance PIR type).
   */
  "5751"?: string;
  /**
   * The current active power.
   */
  "5800"?: number;
  /**
   * The minimum active power measured by the sensor since it is ON.
   */
  "5801"?: number;
  /**
   * The maximum active power measured by the sensor since it is ON.
   */
  "5802"?: number;
  /**
   * The minimum active power that can be measured by the sensor.
   */
  "5803"?: number;
  /**
   * The maximum active power that can be measured by the sensor.
   */
  "5804"?: number;
  /**
   * The total power in Wh that the light has used.
   */
  "5805"?: number;
  /**
   * Request an active power calibration by writing the value of a calibrated load.
   */
  "5806"?: number;
  /**
   * The current reactive power.
   */
  "5810"?: number;
  /**
   * The minimum reactive power measured by the sensor since it is ON.
   */
  "5811"?: number;
  /**
   * The maximum reactive power measured by the sensor since it is ON.
   */
  "5812"?: number;
  /**
   * The minimum active power that can be measured by the sensor.
   */
  "5813"?: number;
  /**
   * The minimum active power that can be measured by the sensor.
   */
  "5814"?: number;
  /**
   * The cumulative reactive power since the last cumulative energy reset or device start.
   */
  "5815"?: number;
  /**
   * Request a reactive power calibration by writing the value of a calibrated load.
   */
  "5816"?: number;
  /**
   * The power factor of the actuactor.
   */
  "5820"?: number;
  /**
   * Read or Write the current calibration coefficient.
   */
  "5821"?: number;
  /**
   * Reset both cumulative active/reactive power.
   */
  "5822"?: string;
  /**
   * The event identifier as a string.
   */
  "5823"?: string;
  /**
   * Time when the load control event will start started.
   */
  "5824"?: number;
  /**
   * The duration of the load control event.
   */
  "5825"?: number;
  /**
   * The criticality of the event.  The device receiving the event will react in an appropriate fashion for the device.
   */
  "5826"?: number;
  /**
   * Defines the maximum energy usage of the receivng device, as a percentage of the device's normal maximum energy usage.
   */
  "5827"?: string;
  /**
   * Defines the duty cycle for the load control event, i.e, what percentage of time the receiving device is allowed to be on.
   */
  "5828"?: number;
  /**
   * This resource represents a power source, which can be controlled, the setting of which is a Boolean value (1,0) where 1 is on and 0 is off
   */
  "5850"?: boolean;
  /**
   * This resource represents dimmer setting, which has an Integer value between 0 and 100 as a percentage.
   */
  "5851"?: number;
  /**
   * The time in seconds that the device has been on. Writing a value of 0 resets the counter.
   */
  "5852"?: number;
  /**
   * A string describing a state for multiple level output such as Pilot Wire.
   */
  "5853"?: string;
  /**
   * The time in seconds since the Off command was sent. Writing a value of 0 resets the counter.
   */
  "5854"?: number;
  /**
   * The setpoint value.
   */
  "5900"?: number;
  /**
   * Delay from the detection state to the clear state in ms.
   */
  "5903"?: number;
  /**
   * Delay from the clear state to the busy state in ms.
   */
  "5904"?: number;
  /**
   * Integer in which each of the bits are associated with specific digital input value. Represented as a binary signed integer in network byte order, and in two's complement representation. Using values in range 0-127 is recommended to avoid ambiguities with byte order and negative values.
   */
  "5910"?: number;
  /**
   * Reset the Bitmap Input value.
   */
  "5911"?: string;
  /**
   * The description of each bit as a string. First instance describes the least significant bit, second instance the second least significant bit.
   */
  "5912"?: string;
  /**
   * A universally unique identifier to identify information
   */
  "5913"?: string;
  /**
   * PLMN - mcc/mnc
   */
  "6030"?: number;
  /**
   * Band indicator
   */
  "6031"?: number;
  /**
   * EARFCN - frequency
   */
  "6032"?: number;
  /**
   * Cell Identity
   */
  "6033"?: number;
  /**
   * PCI (0..504)
   */
  "6034"?: number;
  /**
   * RSRP Value in dBm (-180..-30)
   */
  "6035"?: number;
  /**
   * RSRQ Value in dB (-30..10)
   */
  "6036"?: number;
  /**
   * System Frame Number
   */
  "6037"?: number;
  /**
   * Sub Frame Number
   */
  "6038"?: number;
}
