/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * used with an On/Off switch to report the state of the switch.
 */
export interface OnOffSwitch {
  /**
   * The current state of a digital input.
   */
  "5500"?: boolean;
  /**
   * The cumulative value of active state detected.
   */
  "5501"?: number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
  /**
   * The time in seconds that the device has been on. Writing a value of 0 resets the counter.
   */
  "5852"?: number;
  /**
   * The time in seconds since the Off command was sent. Writing a value of 0 resets the counter.
   */
  "5854"?: number;
}
