/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * used with a generic position actuator from 0 to 100%. This resource optionally allows setting the transition time for an operation that changes the position of the actuator, and for reading the remaining time of the currently active transition
 */
export interface Positioner {
  /**
   * The minimum value that can be measured by the sensor.
   */
  "5519"?: number;
  /**
   * The maximum value that can be measured by the sensor.
   */
  "5520"?: number;
  /**
   * Current position or desired position of a positioner actuator.
   */
  "5536"?: number;
  /**
   * The time expected to move the actuator to the new position.
   */
  "5537"?: number;
  /**
   * The time remaining in an operation.
   */
  "5538"?: number;
  /**
   * The minimum value that can be measured by the sensor
   */
  "5601"?: number;
  /**
   * The maximum value that can be measured by the sensor.
   */
  "5602"?: number;
  /**
   * Reset the Min and Max Measured Values to Current Value.
   */
  "5605"?: string;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
}
