/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * used over a power measurement sensor to report a remote power measurement.  It also provides resources for minimum/maximum measured values and the minimum/maximum range for both active and reactive power. Il also provides resources for cumulative energy, calibration, and the power factor.
 */
export interface PowerMeasurment {
  /**
   * Reset the Min and Max Measured Values to Current Value.
   */
  "5605"?: string;
  /**
   * The current active power.
   */
  "5800"?: number;
  /**
   * The minimum active power measured by the sensor since it is ON.
   */
  "5801"?: number;
  /**
   * The maximum active power measured by the sensor since it is ON.
   */
  "5802"?: number;
  /**
   * The minimum active power that can be measured by the sensor.
   */
  "5803"?: number;
  /**
   * The maximum active power that can be measured by the sensor.
   */
  "5804"?: number;
  /**
   * The total power in Wh that the light has used.
   */
  "5805"?: number;
  /**
   * Request an active power calibration by writing the value of a calibrated load.
   */
  "5806"?: number;
  /**
   * The current reactive power.
   */
  "5810"?: number;
  /**
   * The minimum reactive power measured by the sensor since it is ON.
   */
  "5811"?: number;
  /**
   * The maximum reactive power measured by the sensor since it is ON.
   */
  "5812"?: number;
  /**
   * The minimum active power that can be measured by the sensor.
   */
  "5813"?: number;
  /**
   * The minimum active power that can be measured by the sensor.
   */
  "5814"?: number;
  /**
   * The cumulative reactive power since the last cumulative energy reset or device start.
   */
  "5815"?: number;
  /**
   * Request a reactive power calibration by writing the value of a calibrated load.
   */
  "5816"?: number;
  /**
   * The power factor of the actuactor.
   */
  "5820"?: number;
  /**
   * Read or Write the current calibration coefficient.
   */
  "5821"?: number;
  /**
   * Reset both cumulative active/reactive power.
   */
  "5822"?: string;
}
