/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * used to control a power source, such as a Smart Plug.  It allows a power relay to be turned on or off and its dimmer setting to be control as a % between 0 and 100.
 */
export interface PowerControl {
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750": string;
  /**
   * The total power in Wh that the light has used.
   */
  "5805": number;
  /**
   * The power factor of the actuactor.
   */
  "5820": number;
  /**
   * This resource represents a power source, which can be controlled, the setting of which is a Boolean value (1,0) where 1 is on and 0 is off
   */
  "5850": boolean;
  /**
   * This resource represents dimmer setting, which has an Integer value between 0 and 100 as a percentage.
   */
  "5851": number;
  /**
   * The time in seconds that the device has been on. Writing a value of 0 resets the counter.
   */
  "5852": number;
}
