/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An ascending timer that counts how long time has passed since the timer was started after reset.
 */
export interface PowerupLog {
  /**
   * The tool version that the device supports - used to determine the logging object/resource version to be used for parsing
   */
  "1"?: string;
  /**
   * IMEI of device
   */
  "2"?: string;
  /**
   * IMSI of device
   */
  "3"?: string;
  /**
   * MSISDN of device
   */
  "4"?: string;
  /**
   * Human-readable name of the device
   */
  "10"?: string;
}
