/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * report the state of a momentary action push button control and to count the number of times the control has been operated since the last observation.
 */
export interface PushButton {
  /**
   * The current state of a digital input.
   */
  "5500"?: boolean;
  /**
   * The cumulative value of active state detected.
   */
  "5501"?: number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
}
