/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Radio Link Failure Event
 */
export interface RadioLinkFailureEvent {
  /**
   * The tool version that the device supports - used to determine the logging object/resource version to be used for parsing
   */
  "1"?: string;
}
