/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An ascending timer that counts how long time has passed since the timer was started after reset.
 */
export interface Stopwatch {
  /**
   * The cumulative value of active state detected.
   */
  "5501": number;
  /**
   * The total time in seconds that the timer input is true. Writing a 0 resets the time.
   */
  "5544": number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750": string;
  /**
   * This resource represents a power source, which can be controlled, the setting of which is a Boolean value (1,0) where 1 is on and 0 is off
   */
  "5850": boolean;
}
