/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * report the current time in seconds since January 1, 1970 UTC. There is also a fractional time counter that has a range of less than one second.
 */
export interface Time {
  /**
   * Unix Time. A signed integer representing the number of seconds since Jan 1st, 1970 in the UTC time zone.
   */
  "5506"?: string;
  /**
   * For shorter times of a fraction of a second (i.e. 0.23).
   */
  "5507"?: number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
}
