/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * used to report the state of an up/down control element like a pair of push buttons or a rotary encoder. Counters for increase and decrease operations are provided for counting pulses from a quadrature encoder
 */
export interface UpDownControl {
  /**
   * Indicates an increase control action.
   */
  "5532"?: boolean;
  /**
   * Indicates an decrease control action.
   */
  "5533"?: boolean;
  /**
   * Counts the number of times the increase control has been operated. Writing a 0 resets the counter.
   */
  "5541"?: number;
  /**
   * Counts the times the decrease control has been operated. Writing a 0 resets the counter
   */
  "5542"?: number;
  /**
   * The application type of the sensor or actuator as a string, for instance, “Air Pressure”.
   */
  "5750"?: string;
}
